[package]
name = "ec4rs"
description = "An editorconfig core library in pure safe Rust"
license = "Apache-2.0"
homepage = "https://github.com/TheDaemoness/ec4rs"
repository = "https://github.com/TheDaemoness/ec4rs"
readme = "README.md"
keywords = ["editorconfig"]
categories = ["command-line-utilities", "config", "parser-implementations"]

version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
