# Cheat sheet: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ec4rs"
description = "EditorConfig For Rust"
license = "Apache-2.0"
homepage = "https://github.com/TheDaemoness/ec4rs"
repository = "https://github.com/TheDaemoness/ec4rs"
readme = "README.md"
keywords = ["editorconfig"]
categories = ["config", "parser-implementations"]
edition = "2021"

authors = ["TheDaemoness"]
include = ["/src", "/README.md", "/DOC.md"]
rust-version = "1.56" # 2021 edition
version = "1.0.1"

[workspace]
members = ["tools"]
