# Cheat sheet: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ec4rs"
description = "EditorConfig For Rust"
license = "apache-2.0"
homepage = "https://github.com/TheDaemoness/ec4rs"
repository = "https://github.com/TheDaemoness/ec4rs"
readme = "README.md"
keywords = ["editorconfig"]
categories = ["config", "parser-implementations"]
edition = "2021"

authors = ["TheDaemoness"]
exclude = [".editorconfig"]
rust-version = "1.59" # std::iter::zip
version = "0.1.0"

[workspace]
members = ["tools"]
